### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by StudyingByYourself** [Hansimov/csapp#13]
7.6.2 与静态链接库
我们可以通过为每个标准函数创建一个独立的可**車**定位文件，把它们存放在一个为大家都知道的目录中来解决其中的一些问题。然而，这种方法要求应用程序员显式地链接合适的目标模块到它们的可执行文件中，这是一个容易出错**而旦**耗时的过程：

**Comment by Hansimov** [comment]
Thanks. Already fixed in https://github.com/Hansimov/csapp/commit/6ec719b4d2a67866d219e6a9c3905e4aaa931cec.
