### ISSUE TITLE
lab3 attack lab

### ISSUE THREAD

**Issue by ppdogg** [Hansimov/csapp#26]
ctarget运行后，未输入字符串就直接报错段错误，是我环境问题还是程序问题
rtarget运行正常

**Comment by ppdogg** [comment]
glibc版本太老导致报错，解决[链接](https://stackoverflow.com/questions/77568098/csapp-attack-lab-phase1-segmentation-fault-on-ubuntu22-04)

**Comment by Hansimov** [comment]
多谢补充实验细节！
