### ISSUE TITLE
序言-错别字

### ISSUE THREAD

**Issue by renph** [Hansimov/csapp#4]
https://github.com/Hansimov/csapp/blob/master/publish-info/preface.md

[旁注](https://github.com/Hansimov/csapp/blob/master/publish-info/preface.md#%E6%97%81%E6%B3%A8---%E4%BB%80%E4%B9%88%E6%98%AF%E6%97%81%E6%B3%A8)

例如，**高逵缓存**的行、组和块有什么区别？

应为高速缓存

**Comment by Hansimov** [comment]
多谢，已更正。
